project:
  type: default

format:
  revealjs:
    theme: simple
    slide-number: true
    width: 1400
    height: 990
    margin: 0.04
    chalkboard: true
    include-in-header: includes/mathjax-mhchem.html
    include-after-body:
      - includes/quiz-toggle.html
    css:
      - assets/css/quiz.css
      - assets/css/table.css
    auto-stretch: false  

filters:
  - filters/quiz.lua

html-math-method:
  method: mathjax
